(executable
 (name qif_cnot_verify_e2e)
 (libraries qpl_surface str))

(executable
 (name reader_qif_ocaml_attempt)
 (libraries qpl_surface))

(executable
 (name qswitch_eta_expansion_e2e)
 (libraries qpl_surface str))

(executable
 (name qswitch_eta_endoQ_e2e)
 (libraries qpl_surface str))

(executable
 (name ctrl_ho_eta_e2e)
 (libraries qpl_surface str))

(executable
 (name dist_unequal_width_probe)
 (libraries qpl_surface))

(executable
 (name dist_l_naturality_probe)
 (libraries qpl_surface str))

(executable
 (name phased_map_probe_e2e)
 (libraries qpl_surface str))

(executable
 (name qs2_dummy_sim_e2e)
 (libraries qpl_surface str))

(executable
 (name qs3_pn_dummy_sim_e2e)
 (libraries qpl_surface str))

(executable
 (name algorithms_e2e)
 (libraries qpl_surface str))

(executable
 (name qswitch_instantiated_e2e)
 (libraries qpl_surface str))

(executable
 (name zn_controlled_phase_e2e)
 (libraries qpl_surface str))

(executable
 (name short_circuit_e2e)
 (libraries qpl_surface str))

(executable
 (name datatype_demo)
 (libraries qpl_surface))

(executable
 (name exp_twist_e2e)
 (libraries qpl_surface str))

(executable
 (name abstract_qswitch_oterm_e2e)
 (libraries qpl_surface str))

(executable
 (name ctrl_lambda_e2e)
 (libraries qpl_surface str))

(executable
 (name verify_nested_ctrl_e2e)
 (libraries qpl_surface str))

(executable
 (name abstract_select_2_e2e)
 (libraries qpl_surface str))

(executable
 (name nested_apply_e2e)
 (libraries qpl_surface str))

(executable
 (name nested_select_e2e)
 (libraries qpl_surface str))

(executable
 (name n_plusmap_e2e)
 (libraries qpl_surface str))

(executable
 (name curried_select_3_e2e)
 (libraries qpl_surface str))

(executable
 (name curried_select_3_ndist_e2e)
 (libraries qpl_surface str))

(executable
 (name zn_group_ops_e2e)
 (libraries qpl_surface str))
(executable (name dump_abstract_qswitch) (libraries qpl_surface str))
(executable (name dump_select_5_inst) (libraries qpl_surface str))

(executable
 (name exp_swap_T3_e2e)
 (libraries qpl_surface str))
(executable (name test_first_order) (libraries qpl_surface str))
