(executable
 (name algorithms_e2e)
 (libraries qpl_surface str))

(executable
 (name abstract_qswitch_e2e)
 (libraries qpl_surface str))

(executable
 (name qswitch_instantiated_e2e)
 (libraries qpl_surface str))

(executable
 (name zn_controlled_phase_e2e)
 (libraries qpl_surface str))

(executable
 (name short_circuit_e2e)
 (libraries qpl_surface str))

(executable
 (name linear_demo)
 (libraries qpl_surface))

(executable
 (name datatype_demo)
 (libraries qpl_surface))

(executable
 (name exp_twist_e2e)
 (libraries qpl_surface str))

(executable
 (name abstract_qswitch_oterm_e2e)
 (libraries qpl_surface str))

(executable
 (name ctrl_lambda_e2e)
 (libraries qpl_surface str))
