(** Emit: Generate Python code for the Phase 0-4C pipeline.

    The surface language elaborates to Python AST builder calls.
    This module emits Python code using the existing lang.types and lang.terms.

    NOTE: This module must not depend on Datatype to avoid cycles.
    It takes primitive data (strings, Rep.t, etc.) as arguments.
*)

(** Emit Python code for a type representation.
    Maps to lang.types: Q(), Ten(l, r), Plus(l, r) *)
let rec rep_to_python = function
  | Rep.Var i -> Printf.sprintf "ty_vars[%d]" i
  | Rep.Unit -> "None  # unit type"
  | Rep.Tensor (a, b) ->
    Printf.sprintf "Ten(%s, %s)" (rep_to_python a) (rep_to_python b)
  | Rep.Plus (a, b) ->
    Printf.sprintf "Plus(%s, %s)" (rep_to_python a) (rep_to_python b)

(** Emit Python code for a type with concrete Q() leaves.
    Used when we know all wires are qubits. *)
let rec rep_to_python_concrete = function
  | Rep.Var _ -> "Q()"
  | Rep.Unit -> "None"
  | Rep.Tensor (a, b) ->
    Printf.sprintf "Ten(%s, %s)" (rep_to_python_concrete a) (rep_to_python_concrete b)
  | Rep.Plus (a, b) ->
    Printf.sprintf "Plus(%s, %s)" (rep_to_python_concrete a) (rep_to_python_concrete b)

(** Emit Python code for packing into a constructor.
    Takes datatype name and constructor index. *)
let pack_to_python ~dt_name ~ctor_name ~ctor_idx =
  Printf.sprintf
    "# pack_%s: structural identity (payload already in position %d)\nId(ty_%s)"
    ctor_name ctor_idx dt_name

(** Emit Python code for a case expression with 2 branches.
    Takes constructor payloads and branch bodies. *)
let case_2_to_python ~dt_name ~c0_name ~c0_payload ~c1_name ~c1_payload ~branches =
  let b0_name, b0_body = List.nth branches 0 in
  let b1_name, b1_body = List.nth branches 1 in
  if b0_name = c0_name && b1_name = c1_name then
    Printf.sprintf
      "# case elaboration for %s\n\
       # Branch %s -> %s\n\
       # Branch %s -> %s\n\
       TwistPlus(%s, %s)"
      dt_name
      b0_name b0_body
      b1_name b1_body
      (rep_to_python c0_payload)
      (rep_to_python c1_payload)
  else
    Printf.sprintf
      "# case for %s with custom branch order\n\
       Seq(TwistPlus(%s, %s), ...)"
      dt_name
      (rep_to_python c0_payload)
      (rep_to_python c1_payload)

(** Emit Python code for a general case expression.
    For n > 2 constructors, emits a TODO placeholder. *)
let case_n_to_python ~dt_name ~n =
  Printf.sprintf "# case for %s (%d constructors) - TODO: general elaboration"
    dt_name n

(** Emit Python code for the swap combinator on a 2-constructor datatype. *)
let swap_to_python ~c0_payload ~c1_payload =
  Printf.sprintf "TwistPlus(%s, %s)"
    (rep_to_python c0_payload)
    (rep_to_python c1_payload)

(** Emit Python code for an exponential exp_i(theta, J).

    Precondition: J has been certified as involutive (p o p = id).
    This emits an opaque unitary atom.
*)
let exp_i_to_python ~theta ~j_name ~j_hash =
  Printf.sprintf
    "# exp_i(%f, %s)\n\
     # J certified involutive with hash: %s\n\
     GateAtom(name='exp_i:%s', theta=%f)"
    theta j_name j_hash j_hash theta

(** Emit a complete Python module for a datatype.
    Takes primitive data to avoid Datatype dependency. *)
let emit_datatype_module ~name ~rep ~constructors =
  Printf.sprintf
{|# Auto-generated by QPL surface compiler
# Datatype: %s

from lang.types import Q, Ten, Plus
from lang.terms import Id, Seq, TenTerm, TwistPlus, AssocPlusL, AssocPlusR

# Canonical representation: %s
def make_type(*ty_vars):
    return %s

# Constructors: %s

%s
|}
    name
    (Rep.to_string rep)
    (rep_to_python rep)
    (String.concat ", " (List.map fst constructors))
    (String.concat "\n\n"
      (List.map (fun (cname, cpayload) ->
        Printf.sprintf "# Constructor: %s\n# Payload: %s"
          cname (Rep.to_string cpayload)
      ) constructors))
